# Generated by Django 4.2.6 on 2023-11-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_company_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=4)),
                ('kurs', models.ManyToManyField(to='filter.course')),
            ],
        ),
    ]
