# Generated by Django 4.2.6 on 2023-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_course_alter_company_title_alter_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='receives_scholarship',
            field=models.BooleanField(default=0, max_length=20, verbose_name='Стипендия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=4, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
    ]
