# Generated by Django 4.2.6 on 2023-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_student_receives_scholarship_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='receives_scholarship',
        ),
        migrations.AddField(
            model_name='student',
            name='average_score',
            field=models.FloatField(blank=True, default=float, max_length=20, verbose_name='Средний бал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, max_length=4, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
    ]
