# Generated by Django 4.2.6 on 2023-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_remove_student_receives_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='receives_scholarship',
            field=models.BooleanField(default=bool, max_length=20, verbose_name='Стипендия'),
            preserve_default=False,
        ),
    ]
